<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="Game\Levels\FourPlayerLevel.json" />
    <Content Remove="Game\Levels\TwoPlayerLevel.json" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="Game\Levels\FourPlayerLevel.json" />
    <Compile Include="Game\Levels\TwoPlayerLevel.json" />
  </ItemGroup>

</Project>
